// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAldS50C-aYexDWHQpBBgWpJyqcyyFOHkg',
    appId: '1:858282805262:android:65b76b7c50ba29bd80145f',
    messagingSenderId: '858282805262',
    projectId: 'appfthaha',
    storageBucket: 'appfthaha.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBROesYM1JKMEC0VgRKWyfB02BVU9otbKo',
    appId: '1:858282805262:ios:8491aa6e2c80872280145f',
    messagingSenderId: '858282805262',
    projectId: 'appfthaha',
    storageBucket: 'appfthaha.appspot.com',
    androidClientId: '858282805262-17f7kcr5ftqshhh01am0iriibof6m6cu.apps.googleusercontent.com',
    iosClientId: '858282805262-4lchh53gk099e0gbrnn0inlsbo9d9439.apps.googleusercontent.com',
    iosBundleId: 'com.example.fakeStore',
  );
}
